version: 1.2
workflows:
   - name: primed_phenotype_inventory
     subclass: WDL
     primaryDescriptorPath: /primed_phenotype_inventory.wdl
     testParameterFiles:
         - /primed_phenotype_inventory.json
   - name: primed_genotype_inventory
     subclass: WDL
     primaryDescriptorPath: /primed_genotype_inventory.wdl
     testParameterFiles:
         - /primed_genotype_inventory.json
   - name: primed_association_analysis_inventory
     subclass: WDL
     primaryDescriptorPath: /primed_association_analysis_inventory.wdl
     testParameterFiles:
         - /primed_association_analysis_inventory.json
   - name: primed_ancestry_analysis_inventory
     subclass: WDL
     primaryDescriptorPath: /primed_ancestry_analysis_inventory.wdl
     testParameterFiles:
         - /primed_ancestry_analysis_inventory.json
   - name: primed_inventories
     subclass: WDL
     primaryDescriptorPath: /primed_inventories.wdl
     testParameterFiles:
         - /primed_inventories.json
